name: APP

on: push

jobs:
   lint:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v1
       - uses: michaelw90/PHP-Lint@master         
   build:
     runs-on: ubuntu-latest
     needs: [lint]     

     steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v1    
         with:
           node-version: 8
       - run: npm install
       - run: npm run build 
       - run: cp CHANGELOG.md src/worais-login-protect/CHANGELOG.md       
       - run: cd src/ && zip -r ../../worais-login-protect.zip worais-login-protect
       - uses: actions/upload-artifact@v1
         with:
           name: worais-login-protect
           path: ${{ github.workspace }}/src/